#!/bin/bash
REPO=`git remote -v | grep origin | grep push | awk '{print $2}'`
mkdir gh-pages && \
cp dist/croppy.js gh-pages/ && \
cp example/index.html gh-pages/ && \
cp example/all.css gh-pages/ && \
cp -r example/images gh-pages/ && \
cd gh-pages && \
git init && \
git add . && \
git commit -m 'deploy' && \
git push $REPO master:gh-pages --force && \
cd .. && \
rm -rf gh-pages
